In [1]:
import numpy as np
import talib

np.random.seed(42)
n_timestamps, n_coins = 5, 2

price_data = np.zeros((n_timestamps, n_coins))
price_data[0] = np.random.uniform(100, 1000, n_coins)

for i in range(1, n_timestamps):
    trend = np.random.normal(0.001, 0.02, n_coins)
    price_data[i] = price_data[i - 1] * (1 + trend)

In [2]:
price_data

array([[ 437.08610696,  955.64287577],
       [ 443.1851063 ,  985.70797128],
       [ 441.55282564,  982.07786596],
       [ 455.94049609,  998.13355704],
       [ 452.1153889 , 1009.96263833]])

In [5]:
from indicators2 import ema, sma

ema_fast = ema(price_data, 3)

In [6]:
ema_fast

array([[437.08610696, 955.64287577],
       [440.13560663, 970.67542353],
       [440.84421614, 976.37664474],
       [448.39235611, 987.25510089],
       [450.2538725 , 998.60886961]])

In [11]:
import talib


np.apply_along_axis(lambda x: talib.EMA(x, timeperiod=2), axis=0, arr=price_data)

array([[          nan,           nan],
       [ 440.13560663,  970.67542353],
       [ 441.08041931,  978.27705181],
       [ 450.98713716,  991.51472197],
       [ 451.73930498, 1003.81333287]])

In [20]:
price_data[:, 1]

array([ 955.64287577,  985.70797128,  982.07786596,  998.13355704,
       1009.96263833])

In [ ]:
 ema_fast = np.array(
            [
                talib.EMA(self.close_data[:, i], timeperiod=self.config.ema_fast)
                for i in range(self.n_coins)
            ]
        ).T
        ema_medium = np.array(
            [
                talib.EMA(self.close_data[:, i], timeperiod=self.config.ema_medium)
                for i in range(self.n_coins)
            ]
        ).T
        ema_slow = np.array(
            [
                talib.EMA(self.close_data[:, i], timeperiod=self.config.ema_slow)
                for i in range(self.n_coins)
            ]
        ).T

        signals["ema_fast"] = ema_fast
        signals["ema_medium"] = ema_medium
        signals["ema_slow"] = ema_slow

        signals["ema_fast_above_medium"] = (ema_fast > ema_medium).astype(int)
        signals["price_above_ema_medium"] = (self.close_data > ema_medium).astype(int)
        signals["triple_ema_bullish"] = ((ema_fast > ema_medium) & (ema_medium > ema_slow)).astype(
            int
        )